// Generated by Selenium IDE

import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;

import static org.junit.Assert.*;


public class WidgetsTest extends Hooks {
    private WidgetsPage widgetsPage;

    @Before
    public void setupPageObject() {
        widgetsPage = new WidgetsPage(driver);
    }


    @Test
    public void widgets() {
//        widgetsPage.openWidgets();
        widgetsPage.assertText(widgetsPage.selectMenu, "Select Menu");
//        widgetsPage.openOldStyleSelectMenu();
//        widgetsPage.selectOldStyleSelectMenu("Red");

        widgetsPage.goToWidgetsPage();
//        widgetsPage.fillMandatoryFiledsExcept(widgetsPage.selectMenu);
        driver.close();


//        //look here for solution // instead of by was used webelement
//        widgetsPage.clickWhenReady(widgetsPage.selectMenu);


// how to use @FindBy in another class// makes it public then use it
//        System.out.println(favoritesPage.selectMenu);
    }



}

